# Generated by Django 5.0.7 on 2024-08-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishingcompany',
            name='address',
            field=models.CharField(help_text='Endereço oficial', max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='publishingcompany',
            name='address_complement',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='publishingcompany',
            name='city',
            field=models.CharField(help_text='Cidade', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='publishingcompany',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], help_text='Estado da federação', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='publishingcompany',
            name='zipcode',
            field=models.CharField(help_text='CEP', max_length=20),
        ),
    ]
